@Mediaspot_Api_HostAddress = https://localhost:7064

### Create Video Asset
POST {{Mediaspot_Api_HostAddress}}/assets/video
Content-Type: application/json
Accept: application/json

{
  "externalId": "video-123456",
  "title": "Sample Video",
  "description": "A test video asset",
  "language": "en",
  "durationSeconds": 120.5,
  "resolution": "1920x1080",
  "frameRate": 30,
  "codec": "H264"
}

###

### Create Audio Asset
POST {{Mediaspot_Api_HostAddress}}/assets/audio
Content-Type: application/json
Accept: application/json

{
  "externalId": "audio-123456",
  "title": "Sample Audio",
  "description": "A test audio asset",
  "language": "en",
  "durationSeconds": 180,
  "bitrate": 320,
  "sampleRate": 44100,
  "channels": 2
}

###
@assetId = 3e66a1a6-a924-4b82-a65f-d11e2399e44b

GET {{Mediaspot_Api_HostAddress}}/assets/{{assetId}}

### Register Media File

POST {{Mediaspot_Api_HostAddress}}/assets/{{assetId}}/files?path=media/file/path.mp4&durationSeconds=120.5
Accept: application/json
###

### Update Asset Metadata
PUT {{Mediaspot_Api_HostAddress}}/assets/{{assetId}}/metadata
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated description",
  "language": "en"
}

###

### Archive Asset
POST {{Mediaspot_Api_HostAddress}}/assets/{{assetId}}/archive

###

### Create Title
POST {{Mediaspot_Api_HostAddress}}/titles
Content-Type: application/json
Accept: application/json

{
  "name": "Star Wars: The Phantom Menace",
  "description": "Science-fiction movie",
  "releaseDate": "1999-10-13",
  "type": 1
}

###

@titleId = REMPLACER_PAR_LE_GUID_RETOURNE

### Get Title By Id
GET {{Mediaspot_Api_HostAddress}}/titles/{{titleId}}
Accept: application/json

###

### Get All Titles
GET {{Mediaspot_Api_HostAddress}}/titles
Accept: application/json

###

### Update Title
PUT {{Mediaspot_Api_HostAddress}}/titles/{{titleId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Star Wars: Episode I - The Phantom Menace",
  "description": "Updated science-fiction movie",
  "releaseDate": "1999-10-13",
  "type": 1
}

###